help/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('help/', views.help, name='help'),
]

jack/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _

from two_factor.admin import AdminSiteOTPRequired
from two_factor.urls import urlpatterns as tf_urls

from . import views

if settings.ADMIN_SITE_OTP_REQUIRED:
    admin.site.__class__ = AdminSiteOTPRequired

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('media/<str:filename>/', views.restricted_media, name="restricted_media"),
    path(
        'media/<str:filename>/<int:download>/',
        views.restricted_media,
        name="restricted_media",
    ),
]

urlpatterns += i18n_patterns(
    path('', views.index, name='index'),
    path('', include('help.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include(tf_urls)),
)

admin.site.site_header = _('Jack Admin')
admin.site.site_title = ''
admin.site.index_title = ''

help/models.py
from django.db import models


class HelpSection(models.Model):
    title = models.CharField(max_length=256, blank=True, null=True)
    title_ja = models.CharField(max_length=256, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    content_ja = models.TextField(blank=True, null=True)
    sort = models.IntegerField(default=0)

    class Meta:
        ordering = ['id']


class HelpItem(models.Model):
    section = models.ForeignKey(HelpSection, models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=256, blank=True, null=True)
    title_ja = models.CharField(max_length=256, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    content_ja = models.TextField(blank=True, null=True)
    sort = models.IntegerField(default=0)

    class Meta:
        ordering = ['id']

help/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import HelpSection


def help(request):
    return render(
        request,
        'help.html',
        {
            'section': 'help',
            'sections': HelpSection.objects.all(),
        },
    )

help/templates/help.html
{% extends 'base.html' %}
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %}
{% translate 'Help' %}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">
{% endblock %}

{% block scripts %}
<script type="module" src="{% static 'js/help.js' %}"></script>
{% endblock %}

{% block navbar-brand %}
<a class="nav-link navbar-brand" href="/">
  <span class="icon">💀</span>
  {% translate 'Django-Jack' %}
</a>
{% endblock %}

{% block right-nav-links %}
{% if user.is_authenticated %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'profile' %}">
    <svg class="icon" aria-hidden="true" focusable="false">
      <use xlink:href="/static/img/sprite/icons-account.svg#user"></use>
    </svg>
    {% translate 'Profile' %}
  </a>
</li>
{% endif %}
{% endblock %}

{% block content %}
<div class="container my-3">
  <div class="row">
    <div class="d-md-block sidebar collapse help-sidebar">
      <nav class="navbar help-navbar navbar-dark bg-dark flex-column justify-content-start align-items-stretch py-0 px-3">
        <div id="helpSidebarMenu" class="help-sidebar-menu">
          <a class="navbar-brand" href="#">{% translate 'Help' %}</a>
          <nav class="nav nav-pills flex-column">
            {% for section in sections %}
            <a class="nav-link collapse-nav-link" href="#section-{{ section.id }}">{% if LANGUAGE_CODE == 'ja' and section.title_ja %}{{ section.title_ja }}{% else %}{{ section.title }}{% endif %}</a>
            <nav class="nav nav-pills flex-column mb-2">
              {% for item in section.helpitem_set.all %}
              <a class="nav-link collapse-nav-link ms-3" href="#item-{{ item.id }}">{% if LANGUAGE_CODE == 'ja' and item.title_ja %}{{ item.title_ja }}{% else %}{{ item.title }}{% endif %}</a>
              {% endfor %}
            </nav>
            {% endfor %}
          </nav> <!-- .nav-pills -->
        </div> <!-- .help-sidebar-menu -->
      </nav> <!-- .navbar -->
    </div> <!-- .sidebar -->
    <div class="offcanvas offcanvas-start w-auto" data-bs-scroll="true" tabindex="-1" id="helpOffcanvasMenu" aria-labelledby="helpOffcanvasMenuLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="helpOffcanvasMenuLabel">Help</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div> <!-- .offcanvas-header -->
      <div class="offcanvas-body">
        <nav class="nav nav-pills flex-column">
          {% for section in sections %}
          <a class="nav-link offcanvas-nav-link" href="#section-{{ section.id }}">{% if LANGUAGE_CODE == 'ja' and section.title_ja %}{{ section.title_ja }}{% else %}{{ section.title }}{% endif %}</a>
          <nav class="nav nav-pills flex-column mb-2">
            {% for item in section.helpitem_set.all %}
            <a class="nav-link offcanvas-nav-link ms-3" href="#item-{{ item.id }}">{% if LANGUAGE_CODE == 'ja' and item.title_ja %}{{ item.title_ja }}{% else %}{{ item.title }}{% endif %}</a>
            {% endfor %}
          </nav>
          {% endfor %}
        </nav> <!-- .nav-pills -->
      </div> <!-- .offcanvas-body -->
    </div> <!-- .offcanvas -->
    <div class="col">
      <div id="helpOffcanvasToggler" class="help-offcanvas-toggler navbar-dark d-md-none">
        <button id="helpOffcanvasButton" type="button" class="btn btn-sm btn-primary rounded-pill" data-bs-toggle="offcanvas" data-bs-target="#helpOffcanvasMenu" onclick="blur();">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div> <!-- .help-offcanvas-toggler -->
      <div class="help">
        <h1>{% translate 'Help' %}</h1>
        {% for section in sections %}
        <div class="help-section ms-3">
          <span class="anchor" id="section-{{ section.id }}"></span>
          <h2>{% if LANGUAGE_CODE == 'ja' and section.title_ja %}{{ section.title_ja }}{% else %}{{ section.title }}{% endif %}</h2>
          {% if LANGUAGE_CODE == 'ja' and section.content_ja %}{{ section.content_ja|safe }}{% else %}{{ section.content|safe }}{% endif %}
          {% for item in section.helpitem_set.all %}
          <div class="help-item ms-4">
            <span class="anchor" id="item-{{ item.id }}"></span>
            <h4>{% if LANGUAGE_CODE == 'ja' and item.title_ja %}{{ item.title_ja }}{% else %}{{ item.title }}{% endif %}</h4>
            {% if LANGUAGE_CODE == 'ja' and item.content_ja %}{{ item.content_ja|safe }}{% else %}{{ item.content|safe }}{% endif %}
            {% if not forloop.last %}
            <hr class="mb-4">
            {% endif %}
          </div> <!-- .help-item -->
          {% endfor %}
          <hr class="mb-4">
        </div> <!-- .help-section -->
        {% endfor %}
      </div> <!-- .help -->
    </div> <!-- .col -->
  </div> <!-- .row -->
</div>
{% endblock %}